export enum Utils {
  TITLE_SUCCESS = 'UTILS.TITLE_SUCCESS',
  TITLE_REQUEST = 'UTILS.TITLE_REQUEST',
  TITLE_ERROR = 'UTILS.TITLE_ERROR',
  TITLE_CONFIRM = 'UTILS.TITLE_CONFIRM',
  OK = 'UTILS.OK',
  CLOSE = 'UTILS.CLOSE',
  SAVE = 'UTILS.SAVE'
}

export enum CrudType {
  CLOSE = 1,
  SAVE = 2,
}